import '../../model/action_item.dart';

class ActionCatalog {
  ActionCatalog._();

  static const List<ActionItem> actions = [
    ActionItem(
      id: 'bp_screening',
      title: 'Book Blood Pressure Screening',
      titleBm: 'Tempah Saringan Tekanan Darah',
      titleZh: '预约血压筛查',
      description: 'Get a free BP check at a nearby Klinik Kesihatan this week.',
      descriptionBm: 'Dapatkan pemeriksaan tekanan darah percuma di Klinik Kesihatan berhampiran minggu ini.',
      descriptionZh: '本周在附近的政府诊所进行免费血压检查。',
      category: 'screening',
      impact: 'high',
      timeMinutes: 15,
      targets: ['cardiovascular'],
      habitIds: ['check_bp_reminder'],
      cta: ActionCta(
        type: 'clinic',
        label: 'Find clinics nearby',
        labelBm: 'Cari klinik berhampiran',
        labelZh: '查找附近诊所',
      ),
    ),
    ActionItem(
      id: 'walk_20',
      title: 'Walk 20 Minutes 3x This Week',
      titleBm: 'Berjalan 20 Minit 3x Minggu Ini',
      titleZh: '本周快走 20 分钟，每周 3 次',
      description: 'Brisk walking lowers cardiovascular risk without needing a gym.',
      descriptionBm: 'Berjalan pantas mengurangkan risiko kardiovaskular tanpa perlu ke gim.',
      descriptionZh: '快走有助于降低心血管风险，无需健身房。',
      category: 'activity',
      impact: 'high',
      timeMinutes: 20,
      targets: ['cardiovascular', 'diabetes_complications'],
      habitIds: ['walk_20'],
      cta: ActionCta(
        type: 'habit',
        label: 'Add to daily habits',
        labelBm: 'Tambah ke tabiat harian',
        labelZh: '加入每日习惯',
      ),
    ),
    ActionItem(
      id: 'swap_drinks',
      title: 'Replace Sugary Drinks',
      titleBm: 'Ganti Minuman Bergula',
      titleZh: '用无糖饮品替代含糖饮料',
      description: 'Swap one sugary drink a day for water or unsweetened tea.',
      descriptionBm: 'Ganti satu minuman bergula sehari dengan air atau teh tanpa gula.',
      descriptionZh: '每天用白水或不加糖的茶替代一杯含糖饮料。',
      category: 'diet',
      impact: 'medium',
      timeMinutes: 1,
      targets: ['diabetes_complications', 'cardiovascular'],
      habitIds: ['no_sugary_drink'],
      cta: ActionCta(
        type: 'habit',
        label: 'Track this habit',
        labelBm: 'Jejak tabiat ini',
        labelZh: '追踪此习惯',
      ),
    ),
    ActionItem(
      id: 'brown_rice',
      title: 'Replace White Rice with Brown Rice',
      titleBm: 'Ganti Nasi Putih dengan Nasi Perang',
      titleZh: '用糙米替代白米饭',
      description: 'Can reduce glycemic load by roughly 24% versus white rice.',
      descriptionBm: 'Boleh mengurangkan beban glisemik kira-kira 24% berbanding nasi putih.',
      descriptionZh: '相较白米，可降低约 24% 的升糖负荷。',
      category: 'diet',
      impact: 'medium',
      timeMinutes: 5,
      targets: ['diabetes_complications'],
      habitIds: ['brown_rice_meal'],
      cta: ActionCta(
        type: 'habit',
        label: 'Add meal swap',
        labelBm: 'Tambah pertukaran makanan',
        labelZh: '加入餐食替换',
      ),
    ),
    ActionItem(
      id: 'blood_sugar',
      title: 'Book Blood Sugar Checkup',
      titleBm: 'Tempah Pemeriksaan Gula Dalam Darah',
      titleZh: '预约血糖检查',
      description: 'A fasting glucose test helps catch diabetes risk early.',
      descriptionBm: 'Ujian glukosa berpuasa membantu mengesan risiko diabetes lebih awal.',
      descriptionZh: '空腹血糖检测有助于更早发现糖尿病风险。',
      category: 'screening',
      impact: 'high',
      timeMinutes: 20,
      targets: ['diabetes_complications'],
      habitIds: [],
      cta: ActionCta(
        type: 'clinic',
        label: 'Find Klinik Kesihatan',
        labelBm: 'Cari Klinik Kesihatan',
        labelZh: '查找政府诊所',
      ),
    ),
    ActionItem(
      id: 'quit_support',
      title: 'Start a Smoke-Free Day Plan',
      titleBm: 'Mulakan Rancangan Hari Tanpa Asap',
      titleZh: '开始无烟日计划',
      description: 'Set one smoke-free day this week and note triggers.',
      descriptionBm: 'Tetapkan satu hari tanpa merokok minggu ini dan catat pencetus.',
      descriptionZh: '本周设定一天不吸烟，并记录触发因素。',
      category: 'smoking',
      impact: 'high',
      timeMinutes: 10,
      targets: ['cardiovascular', 'respiratory', 'cancer'],
      habitIds: ['smoke_free_day'],
      cta: ActionCta(
        type: 'habit',
        label: 'Track smoke-free days',
        labelBm: 'Jejak hari tanpa asap',
        labelZh: '追踪无烟日',
      ),
    ),
    ActionItem(
      id: 'hydrate',
      title: 'Drink 8 Glasses of Water',
      titleBm: 'Minum 8 Gelas Air',
      titleZh: '喝 8 杯水',
      description: 'Steady hydration supports energy and reduces sugary drink swaps.',
      descriptionBm: 'Penghidratan yang baik menyokong tenaga dan mengurangkan minuman bergula.',
      descriptionZh: '稳定补水有助于维持精力，并减少含糖饮料。',
      category: 'diet',
      impact: 'low',
      timeMinutes: 2,
      targets: ['diabetes_complications'],
      habitIds: ['drink_water'],
      cta: ActionCta(
        type: 'habit',
        label: 'Track hydration',
        labelBm: 'Jejak penghidratan',
        labelZh: '追踪饮水',
      ),
    ),
    ActionItem(
      id: 'sleep_7',
      title: 'Aim for 7–8 Hours of Sleep',
      titleBm: 'Sasar 7–8 Jam Tidur',
      titleZh: '争取睡足 7–8 小时',
      description: 'Health Age risk is lowest around 7–8 hours of sleep.',
      descriptionBm: 'Risiko Umur Kesihatan paling rendah sekitar 7–8 jam tidur.',
      descriptionZh: '健康年龄相关风险在约 7–8 小时睡眠时最低。',
      category: 'recovery',
      impact: 'medium',
      timeMinutes: 0,
      targets: ['cardiovascular', 'diabetes_complications'],
      habitIds: ['sleep_7'],
      cta: ActionCta(
        type: 'habit',
        label: 'Log sleep',
        labelBm: 'Log tidur',
        labelZh: '记录睡眠',
      ),
    ),
  ];

  static const List<HabitCatalogItem> habits = [
    HabitCatalogItem(
      id: 'walk_20',
      title: 'Walk 20 minutes',
      titleBm: 'Berjalan 20 minit',
      titleZh: '步行 20 分钟',
    ),
    HabitCatalogItem(
      id: 'drink_water',
      title: 'Drink 8 glasses of water',
      titleBm: 'Minum 8 gelas air',
      titleZh: '喝 8 杯水',
    ),
    HabitCatalogItem(
      id: 'no_sugary_drink',
      title: 'Skip sugary drinks',
      titleBm: 'Elak minuman bergula',
      titleZh: '今天不喝含糖饮料',
    ),
    HabitCatalogItem(
      id: 'brown_rice_meal',
      title: 'Choose brown rice once',
      titleBm: 'Pilih nasi perang sekali',
      titleZh: '选一次糙米饭',
    ),
    HabitCatalogItem(
      id: 'smoke_free_day',
      title: 'Stay smoke-free today',
      titleBm: 'Kekal tanpa asap hari ini',
      titleZh: '今天保持无烟',
    ),
    HabitCatalogItem(
      id: 'sleep_7',
      title: 'Aim for 7–8 hours of sleep',
      titleBm: 'Sasar 7–8 jam tidur',
      titleZh: '争取睡足 7–8 小时',
    ),
    HabitCatalogItem(
      id: 'check_bp_reminder',
      title: 'Plan BP screening visit',
      titleBm: 'Rancang lawatan saringan BP',
      titleZh: '计划血压筛查就诊',
    ),
  ];

  static HabitCatalogItem? habitById(String id) {
    final matches = habits.where((h) => h.id == id);
    return matches.isNotEmpty ? matches.first : null;
  }
}
